final/final/Controllers/CartController.cs
using final.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace final.Controllers
{
    public class CartController : UserController
    {
        ECEEntities db = new ECEEntities();

        //DB Dispose
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        // GET: Cart
        public ActionResult Index()
        {
            return View();
        }

        //取得目前購物車頁面
        public ActionResult GetCart()
        {
            return PartialView("_CartPartial");
        }


        //以id加入Product至購物車，並回傳購物車頁面
        public ActionResult AddToCart(int id , string name,string help,int price,int inventory,string owner,[Bind(Include = "Id,Name,Help,Price,Inventory,Owner")]Commodity postback)
        {
            var currentCart = Models.Operation.GetCurrentCart();
            currentCart.AddProduct(id);
            postback.Name = postback.Name;
            postback.Help = postback.Help;
            postback.Price = postback.Price;
            postback.Inventory = postback.Inventory - 1;//扣庫存
            postback.Owner = postback.Owner;
            db.Entry(postback).State = EntityState.Modified;
            db.SaveChanges();
            return PartialView("_CartPartial");
        }

        //清除購物車內指定項目，並回傳購物車頁面
        public ActionResult RemoveFromCart(int id)
        {
            var currentCart = Models.Operation.GetCurrentCart();
            currentCart.RemoveProduct(id);
            return PartialView("_CartPartial");
        }

        //清空購物車，並回傳購物車頁面
        public ActionResult ClearCart()
        {
            var currentCart = Models.Operation.GetCurrentCart();
            currentCart.ClearCart();
            return PartialView("_CartPartial");
        }
    }
}

final/final/Controllers/ManageOrderController.cs
using final.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace final.Controllers
{
    public class ManageOrderController : UserController
    {
        //建立資料庫實體
        ECEEntities db = new ECEEntities();
        
        //DB dispose
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        //訂單首頁
        [Authorize]
        public ActionResult Index()
        {
            string userid = ((FormsIdentity)User.Identity).Name;
            var result = (from i in db.Order where i.Buyer == userid select i).ToList();
            return View(result);
        }

        //訂單資訊
        [HttpGet]
        [Authorize]
        public ActionResult Detail(int id)
        {            
            var result = (from i in db.Order where i.Id == id select i).FirstOrDefault();
            if (result != default(Order))
            {
                return View(result);             
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        //訂單取消
        [HttpPost]
        [Authorize]
        public ActionResult Detail([Bind(Include = "Id,Buyer,Price,State,Content,ReceiverAddress")]Order postback,int id)
        {
            if (postback.State == "false")
            {
                Order order = db.Order.Find(id);
                db.Order.Remove(order);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            else {
                return Content("error");
            }
        }

        //傳送LineNotify訊息
        public ActionResult SendMessage(string Message = "")
        {
            using (HttpClient httpClient = new HttpClient())
            {
                httpClient.BaseAddress = new Uri("https://notify-api.line.me");
                //設定Notify權杖位子
                //23MRZze2HTzxfnf7eASgNF4ciiWkk75q698vYQNvxUW / 8mQ1CesOnXFIyTjPZGyncp7nPb7uZM5I7Vy0ytyVEUW 為Notify權杖碼
                httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", "23MRZze2HTzxfnf7eASgNF4ciiWkk75q698vYQNvxUW");
                //接收前端訊息
                var content = new FormUrlEncodedContent(new[] { new KeyValuePair<string, string>("message", Message) });
                using (HttpResponseMessage message = httpClient.PostAsync("/api/notify", content).Result)
                {
                    //傳送訊息
                    return new HttpStatusCodeResult(message.StatusCode);                   
                }
            }
        }

        //訂單搜尋
        [HttpPost]
        [Authorize]
        public ActionResult Index(int id)
        {
            //儲存查詢出來的Id
            int searchId;

            using (Models.ECEEntities db = new Models.ECEEntities())
            {
                searchId = (from s in db.Order
                            where s.Id == id
                            select s.Id).FirstOrDefault();

            }

            //如果有存在UserId
            if (searchId != 0)
            {
                using (Models.ECEEntities db = new ECEEntities())
                {
                    var result = (from s in db.Order
                                  where s.Id == searchId
                                  select s).ToList();

                    return View(result);
                }
               
            }
            else
            {
                //回傳 空結果 至Index()的View
                return View("Index", new List<Models.Order>());
            }
        }
    }
}

final/final/Controllers/OrderController.cs
using final.Models;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace final.Controllers
{
    public class OrderController : UserController
    {
        //Order頁面
        [Authorize]
        [HttpGet]
        public ActionResult Index()
        {
            int id = int.Parse($"{DateTime.Now:MMddHHmmss}");
            ViewBag.OrderId = id;
            
            return View();
        }

        //宣告LinePay訂單交易所需的字典
        private static Dictionary<string, object> OrderTransactions = new Dictionary<string, object>();

        //設定LinePay的GateWay
        private async Task<string> RequestGateway(string path, object param)
        {
            using (var client = new HttpClient())
            {
                client.DefaultRequestHeaders.Add("X-LINE-ChannelId", "1654190618"); 
                client.DefaultRequestHeaders.Add("X-LINE-ChannelSecret", "8c33b655cf36b77f3f759694dd402d32"); 
                var content = new StringContent(JsonConvert.SerializeObject(param), Encoding.UTF8, "application/json");
                var response = await client.PostAsync("https://sandbox-api-pay.line.me/v2/payments/" + path, content);
                return await response.Content.ReadAsStringAsync();
            }
        }

        //LinePay ReserveAPI(付款)
        [HttpPost]
        public async Task<ActionResult> Reserve(Ship postback, int ItemId, bool capture = true)
        {
            try
            {
                //建立訂單資訊
                var currentcart = Operation.GetCurrentCart();
                var param = new
                {
                    productName = $"訂單編號{postback.OrderID}",
                    productImageUrl = "https://i.imgur.com/DqZUcGd.gif",
                    amount = currentcart.TotalAmount,
                    currency = "TWD",
                    confirmUrl = "http://localhost:50535/Order/Confirm",
                    orderId = $"{postback.OrderID}"
                };               

                //呼叫ReserveAPI
                var responseJson = await RequestGateway("request", param);
                dynamic responseObj = JObject.Parse(responseJson);

                //接收回傳訊息
                if (responseObj.returnCode == "0000")
                {
                    //回傳的交易ID傳回字典
                    OrderTransactions[responseObj.info.transactionId.ToString()] = param;
                    //建立訂單資訊
                    using (ECEEntities db = new ECEEntities())
                    {
                        var content = (from i in db.Commodity select i).FirstOrDefault();
                        string userid = ((FormsIdentity)User.Identity).Name;
                        //建立Order物件
                        var order = new Order()
                        {
                            Id = postback.OrderID,
                            Buyer = userid,
                            Price = currentcart.TotalAmount,
                            Content = $"{currentcart.Content}",
                            ReceiverAddress = postback.ReceiverAddress,
                            State = "false"
                        };
                        //加其入Order資料表後，儲存變更
                        db.Order.Add(order);
                        db.SaveChanges();
                    }
                }
                //取得回傳的Json檔中的付款網址並前往
                string PaymentUrl = responseObj.info.paymentUrl.web;
                return Redirect(PaymentUrl);
            }
            catch (Exception ex)
            {
                return Content(ex.Message);
            }

        }

        //LinePay ConfirmAPI
        [HttpGet]
        public async Task<ActionResult> Confirm(string transactionId, Ship postback)
        {
            //建立Body
            dynamic transaction = OrderTransactions[transactionId];
            var param = new
            {
                amount = transaction.amount,
                currency = "TWD"
            };
            //呼叫Confirm API
            var responseJson = await RequestGateway($"{transactionId}/confirm", param);
            dynamic responseObj = JObject.Parse(responseJson);
            //成功回商品首頁
            if (responseObj.returnCode == "0000")
            {               
                return RedirectToAction("Success","Home",new { orderId = transaction.orderId});
            }
            else
            {
                return Content("Error");
            }
        }

        //傳送LineNotify訊息
        public ActionResult SendMessage(string Message = "")
        {
            using (HttpClient httpClient = new HttpClient())
            {
                httpClient.BaseAddress = new Uri("https://notify-api.line.me");
                //設定Notify權杖位子
                //23MRZze2HTzxfnf7eASgNF4ciiWkk75q698vYQNvxUW / 8hGKfd5tDo30bfIN6485YWuMpoUAcfqOTLcbtABwHR5 為Notify權杖碼
                httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", "23MRZze2HTzxfnf7eASgNF4ciiWkk75q698vYQNvxUW");
                //接收前端訊息
                var content = new FormUrlEncodedContent(new[] { new KeyValuePair<string, string>("message", Message) });
                using (HttpResponseMessage message = httpClient.PostAsync("/api/notify", content).Result)
                {
                    //傳送訊息
                    return new HttpStatusCodeResult(message.StatusCode);
                }
            }
        }
    }
}

final/final/Views/Shared/_CartPartial.cshtml
@{ 
    //取得當前購物車所有內容
    var currentCart = final.Models.Operation.GetCurrentCart();
}
<a id="CartDropDown" class="dropdown-toggle" data-toggle="dropdown">
    @String.Format("共{0}元 ({1})", currentCart.TotalAmount, currentCart.Count)
    <span class="caret"></span>
</a>
<ul class="dropdown-menu" role="menu" aria-labelledby="CartDropDown">
    @if (currentCart.Count > 0)
    {
        foreach (var cartitem in currentCart)
        {
            //依序輸出 ： <li><a>鉛筆<span>100元 x1</span></a></li> .....
            <li class="col-xs-12">
                <span class="col-xs-10">@cartitem.Name @cartitem.Price.ToString("0.0") 元 x @cartitem.Quantity</span>
                <input type="submit" value="X" id="send" class="btn btn-danger col-xs-2" onclick="RemoveFromCart('@cartitem.Id')"/>
             </li>
        }
        <li class="divider"></li>
        <li>
            <div id="CartButtons" class="col-xs-12">
                <a class="btn btn-success text-center col-xs-5" href="@Url.Action("Index", "Order", new { })">結帳</a>
                <input type="submit" value="清空" class="btn btn-danger text-center col-xs-5" onclick="ClearCart()" />
            </div>
        </li>
    }
    else
    {
        <li><a class="btn btn-default text-center" href="#">購物車無任何商品</a></li>
    }
</ul>

final/final/Views/Shared/_CartPartialDisabled.cshtml
@{
    //取得當前購物車所有內容
    var currentCart = final.Models.Operation.GetCurrentCart();
}
<a id="CartDropDown" class="dropdown-toggle" data-toggle="dropdown">
    @String.Format("共{0}元 ({1})", currentCart.TotalAmount, currentCart.Count)
    <span class="caret"></span>
</a>
<ul class="dropdown-menu" role="menu" aria-labelledby="CartDropDown">
    @if (currentCart.Count > 0)
    {
        foreach (var cartitem in currentCart)
        {
            //依序輸出 ： <li><a>鉛筆<span>100元 x1</span></a></li> .....
            <li class="col-xs-12">
                <span class="col-xs-10">@cartitem.Name @cartitem.Price.ToString("0.0") 元 x @cartitem.Quantity</span>
                <input type="submit" value="X" id="send" class="btn btn-danger col-xs-2" onclick="RemoveFromCart('@cartitem.Id')" disabled/>
            </li>
        }
        <li class="divider"></li>
        <li>
            <div id="CartButtons" class="col-xs-12">
                <a class="btn btn-success text-center col-xs-5" href="@Url.Action("Index", "Order", new { })">結帳</a>
                <input type="submit" value="清空" class="btn btn-danger text-center col-xs-5" onclick="ClearCart()" disabled/>
            </div>
        </li>
    }
    else
    {
        <li><a class="btn btn-default text-center" href="#">購物車無任何商品</a></li>
    }
</ul>

final/final/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>前台購物系統</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundels/bootstrap")
    @RenderSection("scripts", false)

    @* 購物車Js *@
    <script type="text/javascript">
        //網頁載入完成時執行之function
        $(document).ready(function () {
            console.log("ready");
        });

        //加入編號為product的商品進購物車
        function AddToCart(productId, productName, productHelp, productInventory, productOwner, productPrice) {
            $.ajax({
                type: 'POST',
                url: '@Url.Action("AddToCart", "Cart")',
                //傳資料庫資料來扣庫存
                data: {
                    id: productId,
                    name: productName,
                    help: productHelp,
                    inventory: productInventory,
                    Price: productPrice,
                    owner:productOwner
                }
            })
            .done(function (msg) {
                //將回傳的購物車頁面 填入 li#Cart
                $('li#Cart').html(msg);
            });
        }

        function RemoveFromCart(productId) {
            $.ajax({
                type: 'POST',
                url: '@Url.Action("RemoveFromCart", "Cart")',
                data: { id: productId }
            })
                .done(function (msg) {
                    //將回傳的購物車頁面 填入li#Cart
                    $('li#Cart').html(msg);
                })
        }

        //清空購物車內所有商品
        function ClearCart() {
            $.ajax({
                type: 'POST',
                url: '@Url.Action("ClearCart", "Cart")',
                data: {}
            })
                .done(function (msg) {
                    //將回傳的購物車頁面 填入 li#Cart
                    $('li#Cart').html(msg);
                })
        }


    </script>

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("首頁","Index","Home")</li>
                    <li>@Html.ActionLink("我的訂單","Index","ManageOrder")</li>
                    <li id="Cart">
                        @Html.Partial("_CartPartial")
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @if (Request.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("登出","Logout","Account")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("註冊","Register","Account", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
                        <li>@Html.ActionLink("登入","Login","Account", routeValues: null, htmlAttributes: new { id = "loginLink" })</li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            @if (Request.IsAuthenticated)
            {
                <p>@ViewBag.UserId 您好</p>
            }
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</body>
</html>

final/final/Views/Shared/_LayoutDisabled.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>前台購物系統</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundels/bootstrap")
    @RenderSection("scripts", false)


</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("首頁", "Index", "Home")</li>
                    <li>@Html.ActionLink("我的訂單", "Index", "ManageOrder")</li>
                    <li id="Cart">
                        @Html.Partial("_CartPartial")
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @if (Request.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("登出", "Logout", "Account")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("註冊", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
                        <li>@Html.ActionLink("登入", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink" })</li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            @if (Request.IsAuthenticated)
            {
                <p>@ViewBag.UserId 您好</p>
            }
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</body>
</html>