EC_Back/EC_Back/Models/Commodity.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC_Back.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    //<--商品內容-->
    public partial class Commodity
    {
        [Display(Name = "商品ID")]
        [Required]
        public int Id { get; set; }

        [Display(Name = "商品名稱")]
        [Required(ErrorMessage = "請輸入正確商品名稱")]
        public string Name { get; set; }

        [Display(Name = "商品說明")]
        [Required(ErrorMessage = "請輸入正確商品說明")]
        public string Help { get; set; }

        [Display(Name = "商品價格")]
        [Required(ErrorMessage = "請輸入正確價格")]
        public int Price { get; set; }

        [Display(Name = "商品庫存")]
        [Required(ErrorMessage = "請輸入正確庫存")]
        public int Inventory { get; set; }

        [Display(Name = "賣家")]
        [Required]
        public string Owner { get; set; }
    }
}

EC_Back/EC_Back/Controllers/CommodityController.cs
using EC_Back.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace EC_Back.Controllers
{
    public class CommodityController : UserController
    {
        //商品DB建立
        ECEEntities db = new ECEEntities();

        //DBDispose
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        //商品頁面Get
        [Authorize]
        public ActionResult CommodIndex()
        {
            List<Commodity> result = new List<Commodity>();
            //商品情況(CRUD)文字呈現
            ViewBag.Result = TempData["Result"];
            //取得登入的Userid
            string userid = ((FormsIdentity)User.Identity).Name;
            //尋找資料與登入的userid符合的商品DB資料
            result = (from i in db.Commodity where i.Owner == userid select i).ToList();
            return View(result);
        }

        //建立商品頁面Get
        [Authorize]
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        //建立商品頁面Post
        [Authorize]
        [HttpPost]
        public ActionResult Create(Commodity post)
        {
            if (ModelState.IsValid)
            {
                //建立商品db
                db.Commodity.Add(post);
                db.SaveChanges();
                TempData["Result"] = string.Format("商品{0}建立成功", post.Name);
                //建立後回首頁
                return RedirectToAction("CommodIndex");
            }           
            ViewBag.Result = "資料輸入錯誤";
            //資料錯誤回首頁
            return View(post);
        }

        //更改商品資料Get
        [HttpGet]
        [Authorize]
        public ActionResult Update(int id)
        {
            var result = (from i in db.Commodity where i.Id == id select i).FirstOrDefault();
            //確認ID無誤進入更改頁面
            if (result != default(Commodity))
            {
                return View(result);
            }
            //錯誤
            else
            {
                TempData["Result"] = "錯誤";
                return RedirectToAction("CommodIndex");
            }
        }

        //更改商品資料Post
        [HttpPost]
        [Authorize]
        public ActionResult Update([Bind(Include = "Id,Name,Help,Price,Inventory,Owner")]Commodity postback)
        {
            //輸入更改資料無誤進行更改
            if (ModelState.IsValid)
            {
                db.Entry(postback).State = EntityState.Modified;
                db.SaveChanges();
                TempData["Result"] = string.Format("商品{0}編輯成功", postback.Name);
                return RedirectToAction("CommodIndex");
            }
            //更改資料錯誤回首頁
            else
            {
                TempData["Result"] = string.Format("找不到該筆資料，請重新確認資料");
                return View(postback);
            }
        }

        //刪除商品資料    
        [HttpPost]
        [Authorize]
        public ActionResult Delete(int id, [Bind(Include = "Id,Name,Help,Price,Inventory,Owner")]Commodity postback)
        {
            var result = (from i in db.Commodity where i.Id == id select i).FirstOrDefault();
            //確認刪除資料無誤進行刪除
            if (result != default(Commodity))
            {
                Commodity commodity = db.Commodity.Find(id);
                db.Commodity.Remove(commodity);
                db.SaveChanges();
                TempData["Result"] = string.Format("商品{0}刪除成功", postback.Name);
                return RedirectToAction("CommodIndex");
            }
            else
            {
                TempData["Result"] = string.Format("找不到該筆資料，請重新確認資料");
                return RedirectToAction("CommodIndex");
            }
        }
    }
}

EC_Back/EC_Back/Views/Commodity/CommodIndex.cshtml
@model List<EC_Back.Models.Commodity>
@{
    ViewBag.Title = "上架商品列表";
}

<h2>上架商品列表</h2>
@if (ViewBag.Result != null)
{
    <h4 class="text-info">@ViewBag.Result</h4>
}
@Html.ActionLink("新增商品", "Create", "Commodity", new { @class = "btn btn-primary" })
<table class="table">
    <thead>
        <tr>            
            <td>編號</td>
            <td>商品名稱</td>
            <td>商品說明</td>
            <td>價格</td>
            <td>庫存</td>
            <td></td>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in this.Model)
        {
        <tr>
            <td style="vertical-align:middle">@item.Id</td>
            <td style="vertical-align:middle">@item.Name</td>
            <td style="vertical-align:middle">@item.Help</td>
            <td style="vertical-align:middle">@item.Price</td>
            <td style="vertical-align:middle">@item.Inventory</td>
            <td>
                @*編輯*@
                @Html.ActionLink("編輯", "Update", "Commodity", new { id = item.Id }, new { @class = "btn btn-info" })
                @*刪除*@
                @using (Html.BeginForm("Delete", "Commodity", FormMethod.Post, new { @class = "Delete" }))
                {
                    @Html.Hidden("Id", item.Id)
                    <input type="submit" value="刪除" class="btn btn-danger" />
                }
            </td>
        </tr>
        }
    </tbody>
</table>

EC_Back/EC_Back/Views/Commodity/Create.cshtml
@model EC_Back.Models.Commodity

@{
    ViewBag.Title = "新增商品";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>新增商品</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @*Id*@
        <div class="form-group">
            @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*ID為系統自動亂數產生 不允許更改*@
                <input name="Id" id="message" value="@ViewBag.ID" readonly class="form-control" />
            </div>
        </div>
        @*Name*@
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        @*Help*@
        <div class="form-group">
            @Html.LabelFor(model => model.Help, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Help, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Help, "", new { @class = "text-danger" })
            </div>
        </div>
        @*Price*@
        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>
        @*Invantory*@
        <div class="form-group">
            @Html.LabelFor(model => model.Inventory, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Inventory, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Inventory, "", new { @class = "text-danger" })
            </div>
        </div>
        @*Owner*@
        <div class="form-group">
            @Html.LabelFor(model => model.Owner, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*Owner為使用者登入帳號 不允許進行更改*@
                <input name="Owner" value="@ViewBag.UserId" readonly class="form-control" />
            </div>
        </div>
        @*送出*@
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="新增商品" id="send" class="btn btn-success" />
                @Html.ActionLink("返回商品資訊", "CommodIndex", "Commodity", new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
}

EC_Back/EC_Back/Views/Commodity/Update.cshtml
@model EC_Back.Models.Commodity

@{
    ViewBag.Title = "商品編輯";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>商品編輯</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.HiddenFor(model => model.Id)

    @*商品名稱*@
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>
    @*商品說明*@
    <div class="form-group">
        @Html.LabelFor(model => model.Help, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Help, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Help, "", new { @class = "text-danger" })
        </div>
    </div>
    @*價格*@
    <div class="form-group">
        @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
        </div>
    </div>
    @*庫存*@
    <div class="form-group">
        @Html.LabelFor(model => model.Inventory, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Inventory, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Inventory, "", new { @class = "text-danger" })
        </div>
    </div>

    @Html.HiddenFor(model => model.Owner)

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="儲存" class="btn btn-success" />
        </div>
        <br />
        <div class="col-md-offset-2 col-md-10">
            @Html.ActionLink("返回商品資訊", "CommodIndex", null, new { @class = "btn btn-default" })
        </div>
    </div>
</div>
}